model_name: "AW-M-1-aimip-w_forcings-woSST_SIC"
type: "daily"
period: "1980-01-01T12:00"
member: "member_01"
sst_scenario: '0' # either '0', '2' or '4' indicating the sst scenario
eval_metrics: 
  bias_map: True
  annual_cycle: True
  latitude_time_plot: True
  radial_spectrum: True
  oceanic_nino_index: False
  indian_monsoon_index: False

evaluator: 
  #path: ["evalstore/${model_name}/${period}/${type}/member_0", "evalstore/${model_name}/${period}/${type}/member_1", "evalstore/${model_name}/${period}/${type}/member_2"]
  model_label: "AWM-1-igt-woSST_SIC-0k"
  reference_dimension_names:
    latitude: latitude
    longitude: longitude
    time: valid_time
    level: pressure_level
  path: "evalstore/${model_name}/${period}/sst_${sst_scenario}/${type}/${member}/data"
  reference_path: "data/era5_1x1/full"
  base_period: [1990, 1998]
  variables: 
    surface: 
      #- "sea_surface_temperature"
      - "2m_temperature"
      #- "mean_sea_level_pressure"
      #- "sea_ice_cover"
    level: 
      - "specific_humidity"
      - "geopotential"
      #- "u_component_of_wind"
      #- "temperature" 
      #- vertical_velocity
  levels: [500, 850]
  output_path: "evalstore/${model_name}/${period}/sst_${sst_scenario}/${type}/${member}"
  start_stamp: "1980-01-01T12:00"
  end_stamp: "1999-12-31T12:00"

evaluate:
  bias_map:
    year: 1999
    
  #annual_anomalies:
  #  plot: True
  #  against_reference: True

  annual_cycle:
    plot: True
    detrend: False
    compare_to_reference: True
    against_reference: True

  latitude_time_plot: 
    time_period: ["1990-01-01T12:00", "1999-12-31T12:00"]
    against_reference: True

  #mean_climate: 
  #  against_reference: True

  radial_spectrum: 
    against_reference: True
    ref_year: 1999

  oceanic_nino_index: 
    power_spectrum: True
    regression_analysis: False
    against_reference: True
    period: ["1980-01-01T12:00", "1999-12-31T12:00"]

  indian_monsoon_index:
    against_reference: True
    period: ["1990-01-01T12:00", "1999-12-31T12:00"]
    kinetic_energy: True

  #anomaly_over_years:
  # variable:  "sea_surface_temperature"
  #  level: Null
  # plot: True
  #  era5: False
  #correlation:
  #  variable1: 
  #    name: "sea_surface_temperature"
  #    level: Null
  #  variable2: 
  #    name: "geopotential"
  #    level: 500
  #  colormap: "coolwarm"
  #  against_reference: True
  #covariance:
  #  variable1: 
  #    name: "sea_surface_temperature"
  #    level: Null
  #  variable2: 
  #    name: "geopotential"
  #    level: 500
  #  plot: True
  #  era5_base: True

  #southern_oscillation_index:
  # plot: True

  #monthly_anomalies:
  #  year: 2020
  #  detrend: False

    

